
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

def opening_gui10():
    from pathlib import Path

    # from tkinter import *
    # Explicit imports to satisfy Flake8
    from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

    from gui9 import opening_gui9
    from gui3 import opening_gui3

    OUTPUT_PATH = Path(__file__).parent
    #ASSETS_PATH = OUTPUT_PATH / Path(r"/home/automatedlogos/Desktop/build/assets/frame10")
    ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/jonja/Documents/GitHub/Automated-Logos/PYTHON/build/assets/frame10") #jon's filepath

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    def open_gui9():
            window.destroy()
            opening_gui9()

    def open_gui3():
            window.destroy()
            opening_gui3()

    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        400.0,
        240.0,
        image=image_image_1
    )

    #button 1 is the NO button
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gui9(),
        relief="flat"
    )
    button_1.place(
        x=519.0,
        y=329.0,
        width=161.0,
        height=75.0
    )

    #button 2 is the YES button
    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gui3(),
        relief="flat"
    )
    button_2.place(
        x=519.0,
        y=215.0,
        width=161.0,
        height=75.0
    )

    canvas.create_rectangle(
        75.0,
        39.0,
        400.0,
        364.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        409.0,
        15.0,
        anchor="nw",
        text=" Are you sure you\n want to delete this\n design?",
        fill="#FFFEFE",
        font=("Inter ExtraBold", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
