
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

def opening_gui9():
    from pathlib import Path

    # from tkinter import *
    # Explicit imports to satisfy Flake8
    from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

    from gui3 import opening_gui3
    from gui11 import opening_gui11
    from gui10 import opening_gui10

    OUTPUT_PATH = Path(__file__).parent
    #ASSETS_PATH = OUTPUT_PATH / Path(r"/home/automatedlogos/Desktop/build/assets/frame9")
    ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/jonja/Documents/GitHub/Automated-Logos/PYTHON/build/assets/frame9") #Jon's filepath

    def relative_to_assets(path: str) -> Path:
        return ASSETS_PATH / Path(path)

    def open_gui3():
            window.destroy()
            opening_gui3()
    
    def open_gui11():
            window.destroy()
            opening_gui11()
    
    def open_gui10():
            window.destroy()
            opening_gui10()

    window = Tk()

    window.geometry("800x480")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 480,
        width = 800,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        400.0,
        240.0,
        image=image_image_1
    )

    #Button 1 is the NO button
    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gui3(),
        relief="flat"
    )
    button_1.place(
        x=531.0,
        y=307.0,
        width=161.0,
        height=75.0
    )

    #Button 2 is the YES button
    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gui11(),
        relief="flat"
    )
    button_2.place(
        x=531.0,
        y=193.0,
        width=161.0,
        height=75.0
    )

    #button 3 is the Delete button
    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: open_gui10(),
        relief="flat"
    )
    button_3.place(
        x=113.0,
        y=387.0,
        width=250.0,
        height=80.0
    )

    canvas.create_rectangle(
        75.0,
        39.0,
        400.0,
        364.0,
        fill="#D9D9D9",
        outline="")

    canvas.create_text(
        452.0,
        15.0,
        anchor="nw",
        text="Is this design\n correct?",
        fill="#FFFEFE",
        font=("Inter ExtraBold", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
